### ISSUE TITLE
软件自动停止运行，提示未能找到文件

### ISSUE THREAD

**Issue by cyp0633** [dimojang/Frogy#13]
正常使用电脑，运行本软件1-2分钟左右，自动退出，似乎不分场景。
![image](https://user-images.githubusercontent.com/16500188/121795498-16f61300-cc44-11eb-945d-ef8eb8a1e0a9.png)
尝试找到这个目录，发现只有一个20210613temp.json。
将数据存储目录迁移至D:\Frogy\FrogyData，仍然会出现闪退情况。
![image](https://user-images.githubusercontent.com/16500188/121795597-d9de5080-cc44-11eb-914a-93150bec38fc.png)
我在使用双显示器，但切断一个之后情况没有消失。
系统Windows 10 Pro 21H1 19043.1052 x64系统+x64软件包。

**Comment by dimojang** [comment]
感谢反馈，已推送修复版本😭😭😭😭

原因是新加入的数据备份机制会在检测数据文件是否存在之前进行。
