### ISSUE TITLE
就离谱

### ISSUE THREAD

**Issue by SouL87a** [dimojang/Frogy#3]
......一个中文开发者，发在IT之家 一个中文论坛 的软件 没有中文。。。 github项目介绍还是中文的
     开发者你说离谱不离谱，虽然，中文用途不大，能看明白。。。

提个建议 开机自启？

**Comment by dimojang** [comment]
嗯啊，因为当时写着写着放飞自我就懒得在XAML里切换输入法了hhh，想着后面就上多语言了。

好的咱会加上的，这个也确实挺必要w

**Comment by dimojang** [comment]
来迟了 功能完成了😭
