### ISSUE TITLE
这个项目还在更新吗

### ISSUE THREAD

**Issue by JiayanJohnnyChu** [dimojang/Frogy#4]

**Comment by dimojang** [comment]
有的，抱歉。
只是最近有些繁忙没有很多时间关注这个项目。
今天晚上肝了个多语言出来，感谢支持！

**Comment by JiayanJohnnyChu** [comment]
在我几天前将下载了0.0.9版本的frogy（之前我用的是0.0.5）并放入program files下并设为开机自启动后，只要我一打开主界面，便会弹出这两个提示框并且退出。希望能将这个问题修复一下。另外能否将frogy上架商店，这样用户方更新会方便一点。谢谢

***@***.******@***.***D75FDA.732DA740]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

**Comment by dimojang** [comment]
请问提示框内容是什么呢

**Comment by JiayanJohnnyChu** [comment]
就是两张图片。
***@***.******@***.***D75FDE.63950D10]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月12日 22:41
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dimojang/Frogy] 这个项目还在更新吗 (#4)


请问提示框内容是什么呢

―

**Comment by dimojang** [comment]
这里好像看不见图片，能留一个额外的社交软件账号

**Comment by JiayanJohnnyChu** [comment]
我的qq：1426917586
另外我在附件里也附上了图片，试试能不能看到

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月12日 23:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dimojang/Frogy] 这个项目还在更新吗 (#4)


这里好像看不见图片，能留一个额外的社交软件账号

―

**Comment by dimojang** [comment]
新的更新已经发布来解决这个问题，感谢反馈！🥳
